---

- hosts: localhost

  tasks:
    - pip:
        extra_args: "--user"
        name: '{{ item }}'
        state: latest
      with_items:
        - neovim
      ignore_errors: true
      tags:
        - all
